/**
 * Turning a paid donation into a voice line, or into nothing at all.
 *
 * Every failure path here returns null rather than throwing. The alert is the
 * product; the voice is an accessory to it, and a donation must never fail to
 * reach the stream because a speech API had a bad minute, a bucket was
 * misconfigured, or nobody set a key.
 */

import { presignUpload, storageConfig } from '@/lib/storage'
import { synthesizeWithAzure, type AzureTtsConfig } from './azure'
import { ttsTextFor, type TtsSubject } from './text'

export { TTS_MAX_CHARS, ttsTextFor, escapeSsml } from './text'

/** Ceiling on the store half of the round trip. See the PUT below. */
const UPLOAD_TIMEOUT_MS = 8_000

/** Azure's Thai neural voices. Premwadee is the female default. */
export const DEFAULT_TTS_VOICE = 'th-TH-PremwadeeNeural'
const DEFAULT_TTS_LOCALE = 'th-TH'

/**
 * Config or null, never a throw — the same contract as storageConfig(), and for
 * the same reason: a deployment with no Azure key must run with TTS off rather
 * than refuse to boot.
 */
export function ttsConfig(): AzureTtsConfig | null {
  const key = process.env.AZURE_SPEECH_KEY
  const region = process.env.AZURE_SPEECH_REGION
  if (!key || !region) return null

  return {
    key,
    region,
    voice: process.env.TTS_VOICE || DEFAULT_TTS_VOICE,
    locale: process.env.TTS_LOCALE || DEFAULT_TTS_LOCALE,
  }
}

/**
 * TTS needs BOTH a speech key and somewhere to put the result. Without a
 * bucket there is nothing to hand the overlay — the audio would have to travel
 * inside the WebSocket frame, which would put ~30KB of base64 into every
 * `/missed` reply.
 */
export function isTtsConfigured(): boolean {
  return ttsConfig() !== null && storageConfig() !== null
}

/**
 * One object per donation, named after it.
 *
 * Deterministic rather than random, unlike an avatar key: a re-synthesis of the
 * same donation is the same sentence and should overwrite rather than
 * accumulate. Nothing user-supplied reaches the key — both ids are generated by
 * the database.
 */
export function ttsKey(streamerId: string, donationId: string): string {
  return `tts/${streamerId}/${donationId}.mp3`
}

export type TtsRequest = TtsSubject & {
  donationId: string
  streamerId: string
  /** The streamer's AlertSetting.ttsEnabled. False here means "do not spend anything". */
  enabled: boolean
  /**
   * AlertSetting.soundVolume, 0-100. The overlay plays the voice line through
   * it, so 0 is not "quiet" — it is inaudible, and synthesising into it is
   * paying for silence.
   */
  volume: number
}

/**
 * Synthesize, store, and return the URL — or null, which is an ordinary
 * outcome and not an error.
 *
 * Null happens for five reasons, in this order, and the order is the point:
 * the streamer has TTS off or the alert volume at zero, nothing is configured,
 * there is nothing worth saying, or the call failed. The first four cost
 * nothing, so they are checked before any network call is made.
 */
export async function synthesizeDonationSpeech(req: TtsRequest): Promise<string | null> {
  if (!req.enabled || req.volume <= 0) return null

  const tts = ttsConfig()
  const storage = storageConfig()
  if (!tts || !storage) return null

  const text = ttsTextFor(req)
  if (!text) return null

  try {
    const speech = await synthesizeWithAzure(tts, text)

    const key = ttsKey(req.streamerId, req.donationId)
    const upload = await presignUpload(storage, key, speech.contentType, speech.audio.byteLength)

    const put = await fetch(upload.uploadUrl, {
      method: 'PUT',
      headers: upload.headers,
      body: speech.audio,
      // The same reasoning as the timeout on the synthesis call, and it has to
      // be on both halves: this runs inside the webhook handler, ahead of the
      // publish, so a hung PUT delays the alert exactly as a hung Azure would.
      signal: AbortSignal.timeout(UPLOAD_TIMEOUT_MS),
    })
    if (!put.ok) {
      console.error(`[tts] upload failed ${put.status} for donation=${req.donationId}`)
      return null
    }

    return upload.publicUrl
  } catch (err) {
    // Logged, not thrown: the caller is the webhook processor, and a donation
    // that is PAID must stay PAID and still reach the overlay.
    console.error(`[tts] synthesis failed for donation=${req.donationId}:`, err)
    return null
  }
}
