/**
 * Turning a paid donation into a voice line, or into nothing at all.
 *
 * Every failure path here returns null rather than throwing. The alert is the
 * product; the voice is an accessory to it, and a donation must never fail to
 * reach the stream because a speech API had a bad minute, a bucket was
 * misconfigured, or nobody set a key.
 */

import { TEST_ALERT_SAMPLE } from '@dp/shared'
import {
  objectExists,
  publicUrlForKey,
  putObject,
  storageConfig,
  type StorageConfig,
} from '@/lib/storage'
import { synthesizeWithAzure, type AzureTtsConfig } from './azure'
import { ttsTextFor, type TtsSubject } from './text'

export { TTS_MAX_CHARS, ttsTextFor, escapeSsml } from './text'

/** Azure's Thai neural voices. Premwadee is the female default. */
export const DEFAULT_TTS_VOICE = 'th-TH-PremwadeeNeural'
const DEFAULT_TTS_LOCALE = 'th-TH'

/**
 * Config or null, never a throw — the same contract as storageConfig(), and for
 * the same reason: a deployment with no Azure key must run with TTS off rather
 * than refuse to boot.
 */
export function ttsConfig(): AzureTtsConfig | null {
  const key = process.env.AZURE_SPEECH_KEY
  const region = process.env.AZURE_SPEECH_REGION
  if (!key || !region) return null

  return {
    key,
    region,
    voice: process.env.TTS_VOICE || DEFAULT_TTS_VOICE,
    locale: process.env.TTS_LOCALE || DEFAULT_TTS_LOCALE,
  }
}

/**
 * TTS needs BOTH a speech key and somewhere to put the result. Without a
 * bucket there is nothing to hand the overlay — the audio would have to travel
 * inside the WebSocket frame, which would put ~30KB of base64 into every
 * `/missed` reply.
 */
export function isTtsConfigured(): boolean {
  return ttsConfig() !== null && storageConfig() !== null
}

/**
 * One object per donation, named after it.
 *
 * Deterministic rather than random, unlike an avatar key: a re-synthesis of the
 * same donation is the same sentence and should overwrite rather than
 * accumulate. Nothing user-supplied reaches the key — both ids are generated by
 * the database.
 */
export function ttsKey(streamerId: string, donationId: string): string {
  return `tts/${streamerId}/${donationId}.mp3`
}

/**
 * Where a test alert's voice line lands.
 *
 * Every input that could change what the file SAYS is in the name, and that is
 * what makes the object reusable instead of merely overwritable. A press whose
 * key already exists is a press that needs no Azure call at all: the sentence
 * is a constant, so the second press and the thousandth are asking for a
 * recording that was already made.
 *
 * The voice, because switching TTS_VOICE must be heard on the next press rather
 * than replaying what the old voice recorded. The fingerprint, because editing
 * TEST_ALERT_SAMPLE must do the same — a reusable object with no version in its
 * name is an object that keeps saying last month's sentence forever, and that
 * trap is the reason this was written as a plain overwrite first.
 *
 * Neither input is typed by a donor, but both land in an object key, so both
 * are stripped down to characters that cannot walk out of the prefix.
 */
export function testTtsKey(streamerId: string, voice: string, fingerprint: string): string {
  const safe = (value: string) => value.replace(/[^A-Za-z0-9-]/g, '-')
  return `tts/${streamerId}/test-${safe(voice)}-${safe(fingerprint)}.mp3`
}

/**
 * Eight hex characters of SHA-256 over the sentence.
 *
 * Long enough that two different sentences colliding is not a thing that
 * happens; short enough to read in a bucket listing. It is a cache key, not a
 * security boundary — nobody gains anything by finding a collision with a
 * string this app chose itself.
 */
async function fingerprintOf(text: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text))
  return Array.from(new Uint8Array(digest).slice(0, 4))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

/** What both callers must clear before anything paid happens. */
type TtsGate = {
  streamerId: string
  /** The streamer's AlertSetting.ttsEnabled. False here means "do not spend anything". */
  enabled: boolean
  /**
   * AlertSetting.soundVolume, 0-100. The overlay plays the voice line through
   * it, so 0 is not "quiet" — it is inaudible, and synthesising into it is
   * paying for silence.
   */
  volume: number
}

export type TtsRequest = TtsSubject & TtsGate & { donationId: string }

/** A test alert says a fixed sentence, so there is no subject to hand over. */
export type TtsTestRequest = TtsGate

/**
 * The half both callers share: say it, store it, hand back the URL.
 *
 * `label` reaches nothing but a log line. It exists because "which donation
 * failed" and "which streamer pressed test" are the two questions asked of
 * these logs, and one of them has no donation id.
 */
async function synthesizeToKey(
  tts: AzureTtsConfig,
  storage: StorageConfig,
  text: string,
  key: string,
  label: string,
): Promise<string | null> {
  let speech: Awaited<ReturnType<typeof synthesizeWithAzure>>
  try {
    speech = await synthesizeWithAzure(tts, text)
  } catch (err) {
    // Logged, not thrown: on the donation path the caller is the webhook
    // processor, and a donation that is PAID must stay PAID and still reach the
    // overlay. The test button has the weaker version of the same need — an
    // alert with no voice still proves the OBS wiring.
    console.error(`[tts] synthesis failed for ${label}:`, err)
    return null
  }

  // The store half has the same must-not-throw contract, and putObject already
  // holds it — including the timeout, for the same reason the synthesis call
  // has one: this runs inside the webhook handler, ahead of the publish.
  return putObject(storage, key, speech.contentType, speech.audio, label)
}

/**
 * Synthesize, store, and return the URL — or null, which is an ordinary
 * outcome and not an error.
 *
 * Null happens for five reasons, in this order, and the order is the point:
 * the streamer has TTS off or the alert volume at zero, nothing is configured,
 * there is nothing worth saying, or the call failed. The first four cost
 * nothing, so they are checked before any network call is made.
 */
export async function synthesizeDonationSpeech(req: TtsRequest): Promise<string | null> {
  if (!req.enabled || req.volume <= 0) return null

  const tts = ttsConfig()
  const storage = storageConfig()
  if (!tts || !storage) return null

  const text = ttsTextFor(req)
  if (!text) return null

  return synthesizeToKey(
    tts,
    storage,
    text,
    ttsKey(req.streamerId, req.donationId),
    `donation=${req.donationId}`,
  )
}

/**
 * The same sentence the test alert puts on screen, spoken.
 *
 * Worth saying at all because without it the only way to find out whether the
 * voice reaches OBS is to wait for a real donation, which is the opposite of
 * what a test button is for.
 *
 * SYNTHESISED AT MOST ONCE per streamer, voice and sentence. The first press
 * pays ~62 characters; every press after it finds the object already there and
 * hands back the same URL. That is what lets this endpoint keep its ordinary
 * 10-a-minute ceiling instead of needing a budget of its own: somebody dragging
 * an OBS source around and pressing test thirty times in a row is doing exactly
 * what the button is for, and it costs nothing after the first.
 *
 * Returns null for the same reasons a donation does — TTS off, muted, nothing
 * configured, or the call failed — and never throws.
 */
export async function synthesizeTestSpeech(req: TtsTestRequest): Promise<string | null> {
  if (!req.enabled || req.volume <= 0) return null

  const tts = ttsConfig()
  const storage = storageConfig()
  if (!tts || !storage) return null

  const text = ttsTextFor(TEST_ALERT_SAMPLE)
  if (!text) return null

  const key = testTtsKey(req.streamerId, tts.voice, await fingerprintOf(text))

  // Asked before paying, and a false answer for any reason — bucket unreachable,
  // a timeout, an odd status — costs one re-synthesis rather than a URL pointing
  // at nothing. objectExists is written to fail in that direction.
  if (await objectExists(storage, key)) return publicUrlForKey(storage, key)

  return synthesizeToKey(tts, storage, text, key, `test streamer=${req.streamerId}`)
}
